name: Spot-me-songs
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - seaborn
  - pyyaml
  - scikit-learn
  - matplotlib
  - jupyter
  - pip=22.1.2=py39haa95532_0
  - pip:
    - spotipy==2.20.0
    - streamlit==1.12.2