Data:
    Hot_100: "../Data/Clean/Hot_100.csv"
    Not_Hot: "../Data/Clean/Not_Hot.csv"
    Hot_100_Data: "../Data/Clean/Hot_100_Data.csv"
    Songs_DB: "../Data/Clean/Songs_DB.csv"
    Songs_Data: "../Data/Clean/Songs_Data.csv"
    Songs_DB_Clusters: "Data/Clean/Songs_DB_Clusters.csv"

Random:
    State: 22

Transformers:
    Power: "Transformers/Power_Transformer.pkl"

Scalers:
    Standard: "Scalers/Standard_Scaler.pkl"

Models:
    K-Means: "Models/KM_28.pkl"
    Gaussian: "Models/GM_15_S.pkl"