Data:
    Songs_DB_Clusters: "Songs_DB_Clusters.csv"

Random:
    State: 22

Transformers:
    Power: "Power_Transformer.pkl"

Scalers:
    Standard: "Standard_Scaler.pkl"

Models:
    K-Means: "KM_28.pkl"